language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --dev

script:
  - bin/phpspec run --format=pretty
